platform :ios, '14.0'

abstract_target 'IrohaCrypto' do
    use_frameworks!

    pod 'IrohaCrypto', :path => '../'
    pod 'secp256k1.c', :git => 'https://github.com/novasamatech/secp256k1.c', :tag => '0.1.3'
    
    target 'IrohaCryptoExample'
    target 'IrohaCryptoTests'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            end
        end
    end
end
